# CuTile attention kernel — generated by renderer
# Grammar hash  : 2dd9d7dd35218bbfa45431d45be4d7bd103a29ea3decd32755fadb98fba070a2
# Kernels        : 8
# Global tensors : ['A', 'P', 'S', 'S_scaled', 'S_shifted', 'l', 'm', 'out']

import math
import torch
import cuda.tile as ct

# ── Kernel 0: MatMul_QK ──
# Loops: SEQ_Q(par) → SEQ_KV(par)
# Grid:  (Bsz*H, SEQ_Q//TILE_Q, SEQ_KV//TILE_KV)
@ct.kernel
def _stage_0_MatMul_QK(_q, _k, S, H: int, D: int, Sq: int, Skv: int):
    TILE_Q  = 64
    TILE_KV = 64
    _inv_scale = 1.0 / math.sqrt(D)

    # Block IDs → (batch, head, tile indices)
    bh_i     = ct.bid(0)  # batch * head
    b        = bh_i // H
    h        = bh_i  % H
    seq_q_i    = ct.bid(1)  # SEQ_Q tile index
    seq_kv_i   = ct.bid(2)  # SEQ_KV tile index

    q_smem = ct.smem((TILE_Q, D))
    ct.copy(_q[b, h, seq_q_i*TILE_Q:(seq_q_i+1)*TILE_Q, :D], q_smem)
    k_smem = ct.smem((TILE_KV, D))
    ct.copy(_k[b, h, seq_kv_i*TILE_KV:(seq_kv_i+1)*TILE_KV, :D], k_smem)
    ct.sync()

    S_tile = ct.rmem((TILE_Q, TILE_KV), fill=0.0)
    # MatMul_QK
    ct.gemm(q_smem, k_smem, S_tile, transpose_b=True)

    ct.copy(S_tile, S[b, h, seq_q_i*TILE_Q:(seq_q_i+1)*TILE_Q, seq_kv_i*TILE_KV:(seq_kv_i+1)*TILE_KV])


# ── Kernel 1: Scale ──
# Loops: SEQ_Q(par) → SEQ_KV(par)
# Grid:  (Bsz*H, SEQ_Q//TILE_Q, SEQ_KV//TILE_KV)
@ct.kernel
def _stage_1_Scale(S, S_scaled, H: int, D: int, Sq: int, Skv: int):
    TILE_Q  = 64
    TILE_KV = 64
    _inv_scale = 1.0 / math.sqrt(D)

    # Block IDs → (batch, head, tile indices)
    bh_i     = ct.bid(0)  # batch * head
    b        = bh_i // H
    h        = bh_i  % H
    seq_q_i    = ct.bid(1)  # SEQ_Q tile index
    seq_kv_i   = ct.bid(2)  # SEQ_KV tile index

    S_smem = ct.smem((TILE_Q, TILE_KV))
    ct.copy(S[b, h, seq_q_i*TILE_Q:(seq_q_i+1)*TILE_Q, seq_kv_i*TILE_KV:(seq_kv_i+1)*TILE_KV], S_smem)
    ct.sync()

    # Scale
    S_scaled_tile = S_smem * _inv_scale

    ct.copy(S_scaled_tile, S_scaled[b, h, seq_q_i*TILE_Q:(seq_q_i+1)*TILE_Q, seq_kv_i*TILE_KV:(seq_kv_i+1)*TILE_KV])


# ── Kernel 2: RowMax ──
# Loops: SEQ_Q(par) → SEQ_KV(ser)
# Grid:  (Bsz*H, SEQ_Q//TILE_Q)
@ct.kernel
def _stage_2_RowMax(S_scaled, m, H: int, D: int, Sq: int, Skv: int):
    TILE_Q  = 64
    TILE_KV = 64
    _inv_scale = 1.0 / math.sqrt(D)

    # Block IDs → (batch, head, tile indices)
    bh_i     = ct.bid(0)  # batch * head
    b        = bh_i // H
    h        = bh_i  % H
    seq_q_i    = ct.bid(1)  # SEQ_Q tile index

    m_acc = ct.rmem((TILE_Q, 1), fill=float('-inf'))  # RowMax accumulator

    # Serial loop over SEQ_KV  (bound=2048, tile=TILE_KV)
    for seq_kv_i in range(2048 // TILE_KV):
        S_scaled_smem = ct.smem((TILE_Q, TILE_KV))
        ct.copy(S_scaled[b, h, seq_q_i*TILE_Q:(seq_q_i+1)*TILE_Q, seq_kv_i*TILE_KV:(seq_kv_i+1)*TILE_KV], S_scaled_smem)
        ct.sync()

        # RowMax
        m_acc = ct.maximum(m_acc, ct.max(S_scaled_smem, axis=1, keepdim=True))

        ct.sync()

    ct.copy(m_acc, m[b, h, seq_q_i*TILE_Q:(seq_q_i+1)*TILE_Q, :1])

# ── Kernel 3: Subtract ──
# Loops: SEQ_Q(par) → SEQ_KV(par)
# Grid:  (Bsz*H, SEQ_Q//TILE_Q, SEQ_KV//TILE_KV)
@ct.kernel
def _stage_3_Subtract(S_scaled, m, S_shifted, H: int, D: int, Sq: int, Skv: int):
    TILE_Q  = 64
    TILE_KV = 64
    _inv_scale = 1.0 / math.sqrt(D)

    # Block IDs → (batch, head, tile indices)
    bh_i     = ct.bid(0)  # batch * head
    b        = bh_i // H
    h        = bh_i  % H
    seq_q_i    = ct.bid(1)  # SEQ_Q tile index
    seq_kv_i   = ct.bid(2)  # SEQ_KV tile index

    S_scaled_smem = ct.smem((TILE_Q, TILE_KV))
    ct.copy(S_scaled[b, h, seq_q_i*TILE_Q:(seq_q_i+1)*TILE_Q, seq_kv_i*TILE_KV:(seq_kv_i+1)*TILE_KV], S_scaled_smem)
    m_smem = ct.smem((TILE_Q, 1))
    ct.copy(m[b, h, seq_q_i*TILE_Q:(seq_q_i+1)*TILE_Q, :1], m_smem)
    ct.sync()

    # Subtract
    S_shifted_tile = S_scaled_smem - m_smem

    ct.copy(S_shifted_tile, S_shifted[b, h, seq_q_i*TILE_Q:(seq_q_i+1)*TILE_Q, seq_kv_i*TILE_KV:(seq_kv_i+1)*TILE_KV])


# ── Kernel 4: Exp ──
# Loops: SEQ_Q(par) → SEQ_KV(par)
# Grid:  (Bsz*H, SEQ_Q//TILE_Q, SEQ_KV//TILE_KV)
@ct.kernel
def _stage_4_Exp(S_shifted, P, H: int, D: int, Sq: int, Skv: int):
    TILE_Q  = 64
    TILE_KV = 64
    _inv_scale = 1.0 / math.sqrt(D)

    # Block IDs → (batch, head, tile indices)
    bh_i     = ct.bid(0)  # batch * head
    b        = bh_i // H
    h        = bh_i  % H
    seq_q_i    = ct.bid(1)  # SEQ_Q tile index
    seq_kv_i   = ct.bid(2)  # SEQ_KV tile index

    S_shifted_smem = ct.smem((TILE_Q, TILE_KV))
    ct.copy(S_shifted[b, h, seq_q_i*TILE_Q:(seq_q_i+1)*TILE_Q, seq_kv_i*TILE_KV:(seq_kv_i+1)*TILE_KV], S_shifted_smem)
    ct.sync()

    # Exp
    P_tile = ct.exp(S_shifted_smem)

    ct.copy(P_tile, P[b, h, seq_q_i*TILE_Q:(seq_q_i+1)*TILE_Q, seq_kv_i*TILE_KV:(seq_kv_i+1)*TILE_KV])


# ── Kernel 5: RowSum ──
# Loops: SEQ_Q(par) → SEQ_KV(ser)
# Grid:  (Bsz*H, SEQ_Q//TILE_Q)
@ct.kernel
def _stage_5_RowSum(P, l, H: int, D: int, Sq: int, Skv: int):
    TILE_Q  = 64
    TILE_KV = 64
    _inv_scale = 1.0 / math.sqrt(D)

    # Block IDs → (batch, head, tile indices)
    bh_i     = ct.bid(0)  # batch * head
    b        = bh_i // H
    h        = bh_i  % H
    seq_q_i    = ct.bid(1)  # SEQ_Q tile index

    l_acc = ct.rmem((TILE_Q, 1), fill=0.0)  # RowSum accumulator

    # Serial loop over SEQ_KV  (bound=2048, tile=TILE_KV)
    for seq_kv_i in range(2048 // TILE_KV):
        P_smem = ct.smem((TILE_Q, TILE_KV))
        ct.copy(P[b, h, seq_q_i*TILE_Q:(seq_q_i+1)*TILE_Q, seq_kv_i*TILE_KV:(seq_kv_i+1)*TILE_KV], P_smem)
        ct.sync()

        # RowSum
        l_acc = l_acc + ct.sum(P_smem, axis=1, keepdim=True)

        ct.sync()

    ct.copy(l_acc, l[b, h, seq_q_i*TILE_Q:(seq_q_i+1)*TILE_Q, :1])

# ── Kernel 6: Divide ──
# Loops: SEQ_Q(par) → SEQ_KV(par)
# Grid:  (Bsz*H, SEQ_Q//TILE_Q, SEQ_KV//TILE_KV)
@ct.kernel
def _stage_6_Divide(P, l, A, H: int, D: int, Sq: int, Skv: int):
    TILE_Q  = 64
    TILE_KV = 64
    _inv_scale = 1.0 / math.sqrt(D)

    # Block IDs → (batch, head, tile indices)
    bh_i     = ct.bid(0)  # batch * head
    b        = bh_i // H
    h        = bh_i  % H
    seq_q_i    = ct.bid(1)  # SEQ_Q tile index
    seq_kv_i   = ct.bid(2)  # SEQ_KV tile index

    P_smem = ct.smem((TILE_Q, TILE_KV))
    ct.copy(P[b, h, seq_q_i*TILE_Q:(seq_q_i+1)*TILE_Q, seq_kv_i*TILE_KV:(seq_kv_i+1)*TILE_KV], P_smem)
    l_smem = ct.smem((TILE_Q, 1))
    ct.copy(l[b, h, seq_q_i*TILE_Q:(seq_q_i+1)*TILE_Q, :1], l_smem)
    ct.sync()

    # Divide
    A_tile = P_smem / l_smem

    ct.copy(A_tile, A[b, h, seq_q_i*TILE_Q:(seq_q_i+1)*TILE_Q, seq_kv_i*TILE_KV:(seq_kv_i+1)*TILE_KV])


# ── Kernel 7: MatMul_PV ──
# Loops: SEQ_Q(par) → SEQ_KV(ser)
# Grid:  (Bsz*H, SEQ_Q//TILE_Q)
@ct.kernel
def _stage_7_MatMul_PV(_v, A, out, H: int, D: int, Sq: int, Skv: int):
    TILE_Q  = 64
    TILE_KV = 64
    _inv_scale = 1.0 / math.sqrt(D)

    # Block IDs → (batch, head, tile indices)
    bh_i     = ct.bid(0)  # batch * head
    b        = bh_i // H
    h        = bh_i  % H
    seq_q_i    = ct.bid(1)  # SEQ_Q tile index

    out_acc = ct.rmem((TILE_Q, D), fill=0.0)  # MatMul_PV accumulator

    # Serial loop over SEQ_KV  (bound=2048, tile=TILE_KV)
    for seq_kv_i in range(2048 // TILE_KV):
        A_smem = ct.smem((TILE_Q, TILE_KV))
        ct.copy(A[b, h, seq_q_i*TILE_Q:(seq_q_i+1)*TILE_Q, seq_kv_i*TILE_KV:(seq_kv_i+1)*TILE_KV], A_smem)
        v_smem = ct.smem((TILE_KV, D))
        ct.copy(_v[b, h, seq_kv_i*TILE_KV:(seq_kv_i+1)*TILE_KV, :D], v_smem)
        ct.sync()

        # MatMul_PV
        ct.gemm(A_smem, v_smem, out_acc)

        ct.sync()

    ct.copy(out_acc, out[b, h, seq_q_i*TILE_Q:(seq_q_i+1)*TILE_Q, :D])

def attention(q, k, v):
    # q, k, v: (B, S, H, D)  float CUDA tensors
    Bsz, Sq, H, D = q.shape
    Skv = k.shape[1]
    dtype  = q.dtype
    device = q.device

    # Permute to (B, H, S, D) for tiled computation
    _q = q.permute(0, 2, 1, 3).contiguous()
    _k = k.permute(0, 2, 1, 3).contiguous()
    _v = v.permute(0, 2, 1, 3).contiguous()

    # Allocate global (cross-kernel) tensors
    S = torch.empty((Bsz, H, Sq, Skv), dtype=dtype, device=device)
    S_scaled = torch.empty((Bsz, H, Sq, Skv), dtype=dtype, device=device)
    m = torch.empty((Bsz, H, Sq, 1), dtype=dtype, device=device)
    S_shifted = torch.empty((Bsz, H, Sq, Skv), dtype=dtype, device=device)
    P = torch.empty((Bsz, H, Sq, Skv), dtype=dtype, device=device)
    l = torch.empty((Bsz, H, Sq, 1), dtype=dtype, device=device)
    A = torch.empty((Bsz, H, Sq, Skv), dtype=dtype, device=device)
    out = torch.empty((Bsz, H, Sq, D), dtype=dtype, device=device)

    # kernel 0: MatMul_QK
    _stage_0_MatMul_QK[(Bsz * H, Sq  // 64, Skv // 64,)](_q, _k, S, H=H, D=D, Sq=Sq, Skv=Skv)
    # kernel 1: Scale
    _stage_1_Scale[(Bsz * H, Sq  // 64, Skv // 64,)](S, S_scaled, H=H, D=D, Sq=Sq, Skv=Skv)
    # kernel 2: RowMax
    _stage_2_RowMax[(Bsz * H, Sq  // 64,)](S_scaled, m, H=H, D=D, Sq=Sq, Skv=Skv)
    # kernel 3: Subtract
    _stage_3_Subtract[(Bsz * H, Sq  // 64, Skv // 64,)](S_scaled, m, S_shifted, H=H, D=D, Sq=Sq, Skv=Skv)
    # kernel 4: Exp
    _stage_4_Exp[(Bsz * H, Sq  // 64, Skv // 64,)](S_shifted, P, H=H, D=D, Sq=Sq, Skv=Skv)
    # kernel 5: RowSum
    _stage_5_RowSum[(Bsz * H, Sq  // 64,)](P, l, H=H, D=D, Sq=Sq, Skv=Skv)
    # kernel 6: Divide
    _stage_6_Divide[(Bsz * H, Sq  // 64, Skv // 64,)](P, l, A, H=H, D=D, Sq=Sq, Skv=Skv)
    # kernel 7: MatMul_PV
    _stage_7_MatMul_PV[(Bsz * H, Sq  // 64,)](_v, A, out, H=H, D=D, Sq=Sq, Skv=Skv)

    # Permute output back to (B, S, H, D)
    return out.permute(0, 2, 1, 3).contiguous()